### ISSUE TITLE
The signed data is now passed blank

### ISSUE THREAD

**Issue by sfwenliu** [reown-com/reown-swift#35]
func requestPersonalSign() async throws {

        guard let address = AppKit.instance.getAddress() else { return }
        try await AppKit.instance.request(.personal_sign(address: address, message: "Hello there!"))

    }
 
When using this method, the signature message displayed in the wallet shows up as empty.

**Comment by sfwenliu** [comment]
use MetaMask wallet

**Comment by llbartekll** [comment]
> use MetaMask wallet

I'm testing sample dapp with Metamask and any other wallet and the message appears
