### ISSUE TITLE
Migrating from WalletConnect -> ReOwn, Error: Symmetric key for topic was not found

### ISSUE THREAD

**Issue by simonmcl** [reown-com/reown-swift#37]
**Describe the bug**
I'm migrating from WalletConnect to Reown. I'm also removing all old references to Pairings, and old calls to `Pair.instance` and `Sign.instance` in favour of `WalletKit.instance` (Note there is a typo in the migration guide: https://docs.reown.com/walletkit/upgrade/from-web3wallet-ios, it says to import `WalletKit` in your code, the import however is named `ReownWalletKit`)

It looks like any pairing/session that was created with WalletConnect can not be disconnected with ReOwn. Only ReOwn sessions can be disconnected, using `try await WalletKit.instance.disconnect(topic: forSession.topic)`. Previous sessions return:

```
Error: Symmetric key for topic 'ed50b3c1ecf9489555fbaf409b51f39cde9f80366318673578ef11bc3f5d3082' was not found.
  - symmetricKeyForTopicNotFound : "ed50b3c1ecf9489555fbaf409b51f39cde9f80366318673578ef11bc3f5d3082"
```

This is a blocker for us upgrading as it means our users will be left with unremoveable sessions

**SDK Version**
 - Client: Swift
 - Version: 1.0.4

**To Reproduce**
Create a Pairing/Session with WalletConnect SDK
Switch to ReOwn, and try to disconnect it

**Comment by llbartekll** [comment]
Pairings will expire by themselves, sessions should not be affected at all. Maybe the session you are trying to remove has already expired.

**Comment by simonmcl** [comment]
@llbartekll I tested again on a clean install and no it doesn't seem to be part of the migration. Pairing on wc2 and then disconnecting with reown does work

I do however have stuck a session though. Thats also not being removed on app delete either. It still has another day left on its expiry:

```
expiryDate : 2024-10-25 09:43:17 +0000
    - timeIntervalSinceReferenceDate : 751542197.0
```

The dApp it was connected to doesn't show this connection, so I can't remove it from that side either. Theres some other issue with being able to delete local references

**Comment by llbartekll** [comment]
Hmm, I don’t think it’s related to migration. 
so you are saying that the WalletKit client returns you a session that you are not able to delete because of the „sym key for topic not found” error, correct?

**Comment by simonmcl** [comment]
@llbartekll correct:

```
let sortedSessions = WalletKit.instance.getSessions().sorted { lhs, rhs in
	return lhs.expiryDate < rhs.expiryDate
}
```

**Comment by llbartekll** [comment]
I will take a look at it

**Comment by llbartekll** [comment]
@simonmcl could you test your issue on [this](https://github.com/reown-com/reown-swift/tree/chore/fix-session-deletion) branch?

**Comment by simonmcl** [comment]
@llbartekll trying to look at this now, but blocked due to this issue: https://github.com/reown-com/reown-swift/issues/45 can you have a look? Seeing weird behaviour on the Swift SDK

**Comment by llbartekll** [comment]
hey @simonmcl, good to hear, Im realising 1.0.5 shortly!
