### ISSUE TITLE
No option to disable analytics collection

### ISSUE THREAD

**Issue by gemcoder21** [reown-com/reown-swift#46]
**Describe the bug**
`WalletKit` does not seem to have any way to disable no consented analytics collection. 

**SDK Version**
 - Version 1.0.4

**To Reproduce**

Open the app with WalletConnect enabled via `WalletKit.configure` and it will be sending analytic events to the `https://pulse.walletconnect.com/batch`

**Expected behavior**

Analytics should not enabled by default and should have ability to enable/disable.

**Screenshots**

<img width="1215" alt="Screenshot 2024-10-30 at 12 18 13 AM" src="https://github.com/user-attachments/assets/20f11b9b-9ea4-43b0-99a9-4ffa91b80c92">

**Comment by simonmcl** [comment]
I would like to turn this off also. We only intend on tracking crash reports and don't want any analytics in our app. This may also cause issues with the privacy disclosure on the app store, with devs unknowingly filling it out incorrectly

**Comment by simonmcl** [comment]
Seems you can disable it via:

```
Events.instance.setTelemetryEnabled(false)
```
