### ISSUE TITLE
App crash after migrate from Web3Wallet to WalletKit 

### ISSUE THREAD

**Issue by nghiepdaocong** [reown-com/reown-swift#47]
**Describe the bug**
I upgraded the app following the guide: https://docs.reown.com/walletkit/upgrade/from-web3wallet-ios but the app crashed after launch with fatalError below:

```
guard let configURL = Bundle.resourceBundle.url(forResource: "PackageConfig", withExtension: "json") else {
            fatalError("Unable to find PackageConfig.json in the resource bundle")
        }
```
I imported lib via: pod 'reown-swift', :git => 'https://github.com/reown-com/reown-swift.git', :tag => '1.0.4'        
**Infomation**
 - Xcode 15.4
 - iPhone 13 - iOs 18.1

**Comment by nghiepdaocong** [comment]
@llbartekll Thank you so much! It work fine when I use SPM.

**Comment by light-cloud** [comment]
Is there any workaround if not possible to switch to SPM because of other dependencies?

**Comment by llbartekll** [comment]
@light-cloud 
> to switch to SPM because of other dependencies?

it's possible to use both package managers

**Comment by llbartekll** [comment]
tho, please check the last cocoapods release
