### ISSUE TITLE
AppKit: Nothing in the usage documentation works

### ISSUE THREAD

**Issue by danscan** [reown-com/reown-swift#51]
**Describe the bug**
From a fresh clone of this repo, opening the `Example` project, setting a project ID in the Configuration file, and running the `AppKitLab` app, the app fails to establish a websocket connection to the relay.

I've tried this with a brand new Reown project/ID, I've tried following the [Relay Client/Networking](https://docs.reown.com/api/core/relay) documentation.

All of which was a last-ditch effort to sanity check why I couldn't get AppKit to work in my app – only to find that not even the official repo's example app works.

In fact, it won't even build in XCode without modifications, because the `@main` App is defined as a class, which causes builds to fail because Apps must be a value type (struct).

Is there anything I'm missing? It seems like this SDK is such a low priority that it's allowed to be this broken :(

**SDK Version**
 - Client: `reown-swift`, `ReownAppKit`

**To Reproduce**
1. Clone this repo.
2. `open Example/ExampleApp.xcodeproj`
3. Uncomment the PROJECT_ID line and paste a Reown Project ID in Configuration.xcconfig
4. Run `AppKitLab`
5. Observe "Socket Disconnected" at the top of the app UI.

**Expected behavior**
Example apps and documentation should demonstrate and describe correct, working behavior.

**Screenshots**
![simulator_screenshot_78BE5356-9837-4C0E-8FD4-EF0EE4C700EE](https://github.com/user-attachments/assets/3cf2d486-69d5-4331-8022-bce679d79374)

**Device (please complete the following information):**
 - Device: iPhone 16 Pro
 - OS: iOS 18.1

**Comment by llbartekll** [comment]
hey @danscan , unfortunately I cannot reproduce it, app compiles and socket connects for me.

**Comment by danscan** [comment]
Here's a demo video of a fresh clone, built with XCode 16.1 to iOS 18.1, demonstrating:
- Crash due to App being a class, not a struct
- Socket failing to connect

Note: I created a new project ID with no domains configured, so that shouldn't be a limitation.

https://github.com/user-attachments/assets/a9eeb64e-a100-412a-9090-ac584363ca7c

**Comment by danscan** [comment]
Screenshot of the behavior on my physical device:

![image](https://github.com/user-attachments/assets/4636e021-0287-4741-9649-9c70c4f909ba)

**Comment by llbartekll** [comment]
hey @danscan, I think the issue started occurring in the latest xcode. Please upgrade to 1.0.7.

**Comment by danscan** [comment]
@llbartekll I just upgraded and built the AppKitLab. It's working now!

FYI there's a snag in the setup process where you need to add an app group and keychain sharing group that I had to figure out from reading the logs and finding the error in the source.

It probably works well out-of-the box when you're part of the walletconnect apple dev org, but if you're not, you can't build the app with its set bundle ID and groups, so you need to change them in both the app info and the AppKitLabApp source.

I'm sure it would save the next person a lot of time to cover that well in the docs :)

**Comment by llbartekll** [comment]
@danscan thanks for your feedback, the group identifier configuration is covered in t[his doc](https://docs.reown.com/api/core/relay). Did you have a chance to see it?


Can we close the issue?

**Comment by danscan** [comment]
Let's go ahead and close. Thank you for addressing the XCode issue!

**Comment by nemanjavlahovic** [comment]
Unfortunately, I'm having this exact same issue :( 

Xcode 16.2
Device: iPhone 12 Pro
OS: iOS 18.1

Have you experienced anything new related to this issue @danscan ?

**Comment by danscan** [comment]
> Unfortunately, I'm having this exact same issue :(

1. Go to the `Signing & Capabilities` tab for your app target in XCode.
2. Add an app group and set the identifier to match your bundle identifier. For example, if your bundle identifier is `com.example.myapp`, your group identifier should be `group.com.example.myapp`.
3. Add a keychain sharing capability and set the identifier to match your bundle identifier, e.g. `com.example.myapp` again.
4. When you call `Networking.configure`, pass `group.com.example.myapp` as the group identifier.

**Comment by winstondu** [comment]
> [@llbartekll](https://github.com/llbartekll) I just upgraded and built the AppKitLab. It's working now!
> 
> FYI there's a snag in the setup process where you need to add an app group and keychain sharing group that I had to figure out from reading the logs and finding the error in the source.
> 
> It probably works well out-of-the box when you're part of the walletconnect apple dev org, but if you're not, you can't build the app with its set bundle ID and groups, so you need to change them in both the app info and the AppKitLabApp source.
> 
> I'm sure it would save the next person a lot of time to cover that well in the docs :)

Oh my god, this was exactly it -- you needed to change the identifier in the AppKitLabApp source. 

This is the worst design ever -- why would the websocket be so completely tied to the keychain group?
